<SCRIPT LANGUAGE=\"Javascript\" TYPE=\"text/javascript\">
<!--

function open_window(url) {
	var NEW_WIN = null;
	NEW_WIN = window.open (\"\", \"RecordViewer\",
							toolbar=\"no\", 
							width=\"400\",
							height=\"600\",
							directories=\"no\",
							status=\"no\",
							scrollbars=\"yes\",
							resize=\"yes\",
							menubar=\"no\");
	NEW_WIN.location.href = url;
}


function sendme() 
{ 
    window.open(\"\",\"myNewWin\",\"width=\"300\",height=\"300\",toolbar=\"0\"); 
    var a = window.setTimeout(\"document.form1.submit();\",500); 
} 
-->
</script>
