<?php

echo "
<TABLE WIDTH=\"65%\" align = \"center\"> 
		<TR> 
  		<TD><IMG SRC=\"../../graphics03/straw99.gif\" ALT=\"StrawHat Auditions (logo)\"ALIGN=\"RIGHT\" BORDER=\"0\"></TD> 
		<TD><IMG SRC=\"../../graphics03/strawhat_banner17_dates-and-deadlines.jpg\" ALIGN=\"CENTER\" ALT=\"StrawHat Auditions\"></TD> 
		</TR> 
</TABLE> 
  
 
<table width=\"66%\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" height=\"43\">
  <tr>
    <td><A HREF=\"../logouttohome.php\" ONMOUSEOVER=\"ReplaceOrig('home');return true;\"
			  ONMOUSEOUT=\"RestoreOrig('home');\"> <IMG SRC=\"../../graphics03/home1.gif\" NAME=\"home\" BORDER=\"0\" ALT=\"Home Page\"
			  WIDTH=\"124\" HEIGHT=\"28\"></A></td> 
	
	<td><A HREF=\"../theatres_search.php\" ONMOUSEOVER=\"ReplaceOrig('theaters');return true;\"
			  ONMOUSEOUT=\"RestoreOrig('theaters');\"> <img src=\"../../graphics03/theaters1.gif\" name=\"theaters\" border=\"0\" alt=\"Attending Theaters\"
			  width=\"124\" height=\"28\"></A></td>

    <td><A HREF=\"../actor_search.php\" ONMOUSEOVER=\"ReplaceOrig('actor');return true;\"
			  ONMOUSEOUT=\"RestoreOrig('actor');\"> <IMG SRC=\"../../graphics03/actor1.gif\" NAME=\"actor\" BORDER=\"0\" ALT=\"Actor Search\"
			  WIDTH=\"124\" HEIGHT=\"28\"></A></td>
			  
    <td><A HREF=\"../articles.php\" 
    ONMOUSEOVER=\"ReplaceOrig('articles');return true;\"
	ONMOUSEOUT=\"RestoreOrig('articles');\"> 
    <IMG SRC=\"../../graphics03/articles1.gif\" NAME=\"articles\" BORDER=\"0\" ALT=\"Articles\"
	WIDTH=\"124\" HEIGHT=\"28\"></A></td>			  
  </tr>

  <tr>
	<td>
    <A HREF=\"../mcontct.php\" 
    ONMOUSEOVER=\"ReplaceOrig('contact');return true;\"	
    ONMOUSEOUT=\"RestoreOrig('contact');\"> 
    <img src=\"../../graphics03/contact1.gif\" name=\"contact\" border=\"0\" alt=\"Contact\"
	width=\"124\" height=\"28\"></A></td>

	<td>
    <A HREF=\"https://www.facebook.com/pages/StrawHat-Auditions/175730289110677\" target=\"myNewWin\" onClick=\"sendme() target=\"myNewWin\" onClick=\"sendme()\"
    
    ONMOUSEOVER=\"ReplaceOrig('facebook');return true;\"    
    ONMOUSEOUT=\"RestoreOrig('facebook');\">
    <IMG SRC=\"../../graphics03/facebook_button1.gif\" WIDTH=\"124\" HEIGHT=\"28\"    
    NAME=\"facebook\" BORDER=\"0\" ALT=\"StrawHat on FaceBook\" WIDTH=\"124\" HEIGHT=\"28\">
    </A>
    
    
";    
/*  
    HACKED FORUM, WILL FIX 12/12/12
    <A HREF=\"http://www.strawhat-auditions.com/smf\" 
	ONMOUSEOVER=\"ReplaceOrig('forum');return true;\"
	ONMOUSEOUT=\"RestoreOrig('forum');\"
	target=\"myNewWin\" onClick=\"sendme()\"> 
	<IMG SRC=\"../../graphics03/forum1.gif\" NAME=\"forum\" BORDER=\"0\" ALT=\"StrawHat Forum\" WIDTH=\"124\" HEIGHT=\"28\"></A>
*/  
echo "  
    </td>

    <td><A HREF=\"../techie_search.php\" ONMOUSEOVER=\"ReplaceOrig('tech');return true;\"
			  ONMOUSEOUT=\"RestoreOrig('tech');\"> <IMG SRC=\"../../graphics03/tech1.gif\" NAME=\"tech\" BORDER=\"0\" ALT=\"Tech Site\"
			  WIDTH=\"124\" HEIGHT=\"28\"></A></td>

    <td><A HREF=\"../faq.php\" ONMOUSEOVER=\"ReplaceOrig('faqs');return true;\"
			  ONMOUSEOUT=\"RestoreOrig('faqs');\"> <IMG SRC=\"../../graphics03/faq1.gif\" NAME=\"faqs\" BORDER=\"0\" ALT=\"Frequently Asked Questions\"
			  WIDTH=\"124\" HEIGHT=\"28\"></A></td>


  </tr>
</table> 
";
?>