<SCRIPT LANGUAGE=\"Javascript\" TYPE=\"text/javascript\">
<!--

function open_window(url) {
	var NEW_WIN = null;
	NEW_WIN = window.open (\"\", \"RecordViewer\",
							location=\"0\",
							toolbar=\"0\", 
							width=\"300\",
							directories=\"no\",
							status=\"no\",
							scrollbars=\"yes\",
							resize=\"yes\";
NEW_WIN.location.href = url;
NEW_WIN.focus();
}


function sendme() 
{ 
    window.open(\"\",\"myNewWin\",
	location=\"0\";
	width=\"300\",
	resize=\"yes\",
	scrollbars=\"yes\",
	height=\"300\",
	toolbar=\"0\");
	myNewWin.focus(); 
    var a = window.setTimeout(\"document.form1.submit();\",\"500\"); 
} 
--> 
</script>
