<div align="center">
<table>
	<tr>
	<td><img src="../straw99.gif" width="127" height="97"></td>
	
	<td>


<table width=\"75%\" border=\"1\" align=\"center\">
  <tr>
    <td colspan="5"><a href="../admin_menu05.htm">Return to Admin Menu</a></td>
  </tr>		  


  <tr>
    <td><b>ADD</b></td>
    <td><a href="add_actor04.htm">Actor</a></td>
    <td><a href="add_physical04.php">Physical</a></td>
    <td><a href="add_skills04.php">Skills</a></td>
    <td><a href="add_roles04.php">Roles</a></td>
  </tr>
  <tr>
    <td><b>CHANGE</b></td>
    <td><a href="actor_modifyrecord.php">Actor</a></td>
    <td><a href="physical_modifyrecord.php">Physical</a></td>
    <td><a href="skills_modifyrecord.php">Skills</a></td>
    <td><a href="roles_modifyrecord.php">Roles</a></td>
  </tr>
</table>

	</td>
	</tr>
</table>
</div>