<div align="center">
<TABLE WIDTH="75%"> 
		<TR> 
		<td>
        <a href="../../index.php"><IMG SRC="../../graphics03/straw99.gif"
              ALT="Back to Home Page... Actors, Singers, Dancers, Staff, Tech, Design Apply Now!" 
              WIDTH="127" HEIGHT="97" border="0" align = "right">
        </a>
        </td>
        <TD><IMG SRC="/graphics03/strawhat_banner17_dates-and-deadlines.jpg" ALIGN="CENTER" ALT="StrawHat Auditions"></TD> 
		</TR> 
</TABLE> 

</div>