   	  if($largecity == "Albuquerque") {
	  	echo "
          <option selected value="Albuquerque">Albuquerque</option>"; }
		else {echo "
          <option value="Albuquerque">Albuquerque</option>";}

	  if($largecity == "Anchorage") {
	  	echo "
          <option selected value=\"Anchorage\">Anchorage</option>"; }
		else {echo "
          <option value=\"Anchorage\">Anchorage</option>";}
        
   	  if($largecity == "Atlanta") {
	  	echo "
          <option selected value=\"Atlanta\">Atlanta</option>"; }
		else {echo "
          <option value=\"Atlanta\">Atlanta</option>";}

	  if($largecity == "Baltimore") {
	  	echo "
          <option selected value=\"Baltimore\">Baltimore</option>"; }
		else {echo "
          <option value=\"Baltimore\">Baltimore</option>";}

      if($largecity == "Billings") {
	  	echo "
          <option selected value=\"Billings\">Billings</option>"; }
		else {echo "
          <option value=\"Billings\">Billings</option>";}
        
      if($largecity == "Birmingham") {
	  	echo "
          <option selected value=\"Birmingham\">Birmingham</option>"; }
		else {echo "
          <option value=\"Birmingham\">Birmingham</option>";}
        
      if($largecity == "Boise") {
	  	echo "
          <option selected value=\"Boise\">Boise</option>"; }
		else {echo "
          <option value=\"Boise\">Boise</option>";}

      if($largecity == "Boston") {
	  	echo "
          <option selected value=\"Boston\">Boston</option>"; }
		else {echo "
          <option value=\"Boston\">Boston</option>";}
          
      if($largecity == "Bridgeport") {
	  	echo "
          <option selected value=\"Bridgeport\">Bridgeport</option>"; }
		else {echo "
          <option value=\"Bridgeport\">Bridgeport</option>";}
          
      if($largecity == "Burlington") {
	  	echo "
          <option selected value=\"Burlington\">Burlington</option>"; }
	  	
		else {echo "
          <option value=\"Burlington\">Burlington</option>";}

      if($largecity == "Charleston") {
	  	echo "
          <option selected value=\"Charleston\">Charleston</option>"; }
		else {echo "
          <option value=\"Charleston\">Charleston</option>";}

	  if($largecity == "Charlotte") {
	  	echo "
          <option selected value=\"Charlotte\">Charlotte</option>"; }
		else {echo "
          <option value=\"Charlotte\">Charlotte</option>";}

      if($largecity == "Cheyenne") {
	  	echo "
          <option selected value=\"Cheyenne\">Cheyenne</option>"; }
		else {echo "
          <option value=\"Cheyenne\">Cheyenne</option>";}          
         
	  if($largecity == "Chicago") {
	  	echo "
          <option selected value=\"Chicago\">Chicago</option>"; }
		else {echo "
          <option value=\"Chicago\">Chicago</option>";}
          
      if($largecity == "Columbia") {
	  	echo "
          <option selected value=\"Columbia\">Columbia</option>"; }
		else {echo "
          <option value=\"Columbia\">Columbia</option>";}          
         
	  if($largecity == "Columbus") {
	  	echo "
          <option selected value=\"Columbus\">Columbus</option>"; }
		else {echo "
          <option value=\"Columbus\">Columbus</option>";}
          
      if($largecity == "Denver") {
	  	echo "
          <option selected value=\"Denver\">Denver</option>"; }
		else {echo "
          <option value=\"Denver\">Denver</option>";}          

	  if($largecity == "Detroit") {
	  	echo "
          <option selected value=\"Detroit\">Detroit</option>"; }
		else {echo "
          <option value=\"Detroit\">Detroit</option>";}
          
      if($largecity == "Des Moines") {
	  	echo "
          <option selected value=\"Des Moines\">Des Moines</option>"; }
		else {echo "
          <option value=\"Des Moines\">Des Moines</option>";}          
          
	  if($largecity == "Fargo") {
	  	echo "
          <option selected value=\"Detroit\">Fargo</option>"; }
		else {echo "
          <option value=\"Fargo\">Fargo</option>";}
          
      if($largecity == "Honolulu") {
	  	echo "
          <option selected value=\"Honolulu\">Honolulu</option>"; }
		else {echo "
          <option value=\"Honolulu\">Honolulu</option>";}          
          
	  if($largecity == "Houston") {
	  	echo "
          <option selected value=\"Houston\">Houston</option>"; }
		else {echo "
          <option value=\"Houston\">Houston</option>";}
          
      if($largecity == "Indianapolis") {
	  	echo "
          <option selected value=\"Indianapolis\">Indianapolis</option>"; }
		else {echo "
          <option value=\"Indianapolis\">Indianapolis</option>";}          

	  if($largecity == "Jackson") {
	  	echo "
          <option selected value=\"Jackson\">Jackson</option>"; }
		else {echo "
          <option value=\"Jackson\">Jackson</option>";}
          
      if($largecity == "Jacksonville") {
	  	echo "
          <option selected value=\"Jacksonville\">Jacksonville</option>"; }
		else {echo "
          <option value=\"Jacksonville\">Jacksonville</option>";}          
          
	  if($largecity == "Lewiston") {
	  	echo "
          <option selected value=\"Lewiston\">Lewiston</option>"; }
		else {echo "
          <option value=\"Lewiston\">Lewiston</option>";}
          
      if($largecity == "Little Rock") {
	  	echo "
          <option selected value=\"Little Rock\">Little Rock</option>"; }
		else {echo "
          <option value=\"Little Rock\">Little Rock</option>";}          

      if($largecity == "Los Angeles") {
	  	echo "
          <option selected value=\"Los Angeles\">Los Angeles</option>"; }
		else {echo "
          <option value=\"Los Angeles\">Los Angeles</option>";}
          
      if($largecity == "Louisville") {
	  	echo "
          <option selected value=\"Louisville\">Louisville</option>"; }
		else {echo "
          <option value=\"Louisville\">Louisville</option>";} 
		
      if($largecity == "Louisville") {
	  	echo "
          <option selected value=\"Louisville\">Louisville</option>"; }
		else {echo "
          <option value=\"Louisville\">Louisville</option>";}          

      if($largecity == "Minneapolis") {
	  	echo "
          <option selected value=\"Minneapolis\">Minneapolis</option>"; }
		else {echo "
          <option value=\"Minneapolis\">Minneapolis</option>";}
          
      if($largecity == "Manchester") {
	  	echo "
          <option selected value=\"Manchester\">Manchester</option>"; }
		else {echo "
          <option value=\"Manchester\">Manchester</option>";}          

      if($largecity == "Memphis") {
	  	echo "
          <option selected value=\"Memphis\">Memphis</option>"; }
		else {echo "
          <option value=\"Memphis\">Memphis</option>";}
          
      if($largecity == "Milwaukee") {
	  	echo "
          <option selected value=\"Milwaukee\">Milwaukee</option>"; }
		else {echo "
          <option value=\"Milwaukee\">Milwaukee</option>";}          
          
      if($largecity == "Newark") {
	  	echo "
          <option selected value=\"Newark\">Newark</option>"; }
		else {echo "
          <option value=\"Newark\">Newark</option>";}
          
      if($largecity == "New Orleans") {
	  	echo "
          <option selected value=\"New Orleans\">New Orleans</option>"; }
		else {echo "
          <option value=\"New Orleans\">New Orleans</option>";}                    
          
      if($largecity == "New York City") {
	  	echo "
          <option selected value=\"New York City\">New York City</option>"; }
		else {echo "
          <option value=\"New York City\">New York City</option>";}
          
      if($largecity == "Oklahoma City") {
	  	echo "
          <option selected value=\"Oklahoma City\">Oklahoma City</option>"; }
		else {echo "
          <option value=\"Oklahoma City\">Oklahoma City</option>";}                    

      if($largecity == "Omaha") {
	  	echo "
          <option selected value=\"Omaha\">Omaha</option>"; }
		else {echo "
          <option value=\"Omaha\">Omaha</option>";}
          
      if($largecity == "Phoenix") {
	  	echo "
          <option selected value=\"Phoenix\">Phoenix</option>"; }
		else {echo "
          <option value=\"Phoenix\">Phoenix</option>";}                    
          
      if($largecity == "Philadelphia") {
	  	echo "
          <option selected value=\"Philadelphia\">Philadelphia</option>"; }
		else {echo "
          <option value=\"Philadelphia\">Philadelphia</option>";}
          
      if($largecity == "Portland") {
	  	echo "
          <option selected value=\"Portland\">Portland</option>"; }
		else {echo "
          <option value=\"Portland\">Portland</option>";}                    
          
      if($largecity == "Providence") {
	  	echo "
          <option selected value=\"Providence\">Providence</option>"; }
		else {echo "
          <option value=\"Providence\">Providence</option>";}
          
      if($largecity == "Salt Lake City") {
	  	echo "
          <option selected value=\"Salt Lake City\">Salt Lake City</option>"; }
		else {echo "
          <option value=\"Salt Lake City\">Salt Lake City</option>";}                    

      if($largecity == "Seattle") {
	  	echo "
          <option selected value=\"Seattle\">Seattle</option>"; }
		else {echo "
          <option value=\"Seattle\">Seattle</option>";}
          
      if($largecity == "Sioux Falls") {
	  	echo "
          <option selected value=\"Sioux Falls\">Sioux Falls</option>"; }
		else {echo "
          <option value=\"Sioux Falls\">Sioux Falls</option>";}                    
          
      if($largecity == "Virginia Beach") {
	  	echo "
          <option selected value=\"Virginia Beach\">Virginia Beach</option>"; }
		else {echo "
          <option value=\"Virginia Beach\">Virginia Beach</option>";}
          
      if($largecity == "Wichita") {
	  	echo "
          <option selected value=\"Wichita\">Wichita</option>"; }
		else {echo "
          <option value=\"Wichita\">Wichita</option>";}                    

      if($largecity == "Wilmington") {
	  	echo "
          <option selected value=\"Wilmington\">Wilmington</option>"; }
		else {echo "
          <option value=\"Wilmington\">Wilmington</option>";}