<div align="center">
<TABLE WIDTH="85%" align="center"> 
		<TR> 
  		
<TD>          
<a href="../../index.php">
    <IMG SRC="/graphics03/straw99.gif" ALIGN="right" WIDTH="127" HEIGHT="97" border="0" 
    ALT="Back to Home Page... Actors, Singers, Dancers, Staff, Tech, Design Appy Now!">
    </a>                
</TD>        
        
<!--        <TD><IMG SRC="/graphics03/straw99.gif" ALT="StrawHat Auditions (logo)"ALIGN="RIGHT" BORDER="0"></TD> 
-->		
        
        <TD><IMG SRC="/graphics03/strawhat_banner17_dates-and-deadlines.jpg" ALIGN="CENTER" ALT="StrawHat Auditions"></TD> 
		</TR> 
</TABLE> 

</div>